remote_theme: tedivm/jekyll-theme-portfolio
title: Maha Gasim
author: Maha Gasim
email: mahagasim@gmail.com
description: A short tagline or summary
github_username: mahagasim
linkedin_username: yourlinkedin
